set(_CATKIN_CURRENT_PACKAGE "myproject")
set(myproject_VERSION "0.0.0")
set(myproject_MAINTAINER "superbai <superbai@qq.com>")
set(myproject_PACKAGE_FORMAT "1")
set(myproject_BUILD_DEPENDS "roscpp")
set(myproject_BUILD_EXPORT_DEPENDS "roscpp")
set(myproject_BUILDTOOL_DEPENDS "catkin")
set(myproject_BUILDTOOL_EXPORT_DEPENDS )
set(myproject_EXEC_DEPENDS "roscpp")
set(myproject_RUN_DEPENDS "roscpp")
set(myproject_TEST_DEPENDS )
set(myproject_DOC_DEPENDS )
set(myproject_URL_WEBSITE "")
set(myproject_URL_BUGTRACKER "")
set(myproject_URL_REPOSITORY "")
set(myproject_DEPRECATED "")